import { defineMessages } from '@edx/frontend-platform/i18n';

const messages = defineMessages({
  terms: {
    id: 'title',
    defaultMessage: 'Terms of use',
  },
  subtitle1: {
    id: 'subtitle1',
    defaultMessage: 'Terms and Conditions for PANORAMA',
  },
  point1: {
    id: 'point1',
    defaultMessage: "Welcome to PANORAMA, a learner analytics service provided by Aulasneo. By accessing or using our service, you agree to be bound by the terms and conditions set forth below. If you do not agree with any part of these terms, you should not use our services.",
  },
  subtitle2: {
    id: 'subtitle2',
    defaultMessage: "Data Security and Privacy"
  },
  point2_1: {
    id: 'point2_1',
    defaultMessage: "All data shared with or generated by PANORAMA will be stored on secure servers. We are committed to maintaining the confidentiality, integrity, and security of your data.",
  },
  point2_2: {
    id: 'point2_2',
    defaultMessage: "Users have the right to request the deletion of all their data from our service. Such requests should be made in writing to ",
  },
  point2_3: {
    id: 'point2_3',
    defaultMessage: "We will process your request in a timely manner, in accordance with applicable legal requirements.",
  },
  subtitle3: {
    id: 'subtitle3',
    defaultMessage: "Marketing Communications",
  },
  point3_1: {
    id: 'point3_1',
    defaultMessage: "By creating an account with PANORAMA, you agree that Aulasneo may send you marketing emails related to your service. These emails may include information about new features, updates, promotional offers, and other relevant information concerning our service.",
  },
  point3_2: {
    id: 'point3_2',
    defaultMessage: "Aulasneo is committed to respecting your privacy and ensuring that the content of these communications is relevant and valuable to you.",
  },
  point3_3: {
    id: 'point3_3',
    defaultMessage: "You have the option to opt-out of receiving marketing emails at any time. Each marketing email will include a link or instructions on how to unsubscribe from future communications. Please note that opting out of marketing emails does not preclude Aulasneo from sending you important service-related communications, such as notifications about your account or transactions.",
  },
  subtitle4: {
    id: 'subtitle4',
    defaultMessage: "Modifications to Terms and Conditions and Pricing",
  },
  point4_1: {
    id: 'point4_1',
    defaultMessage: "Aulasneo reserves the right, at its sole discretion, to modify or replace any part of these Terms and Conditions at any time. This includes, but is not limited to, changes in the pricing of our services offered. Such changes may reflect adjustments in our service offerings, changes in the market or legal environment, or updates to our business model. Users will be notified of any significant changes to the terms and pricing through the email address associated with their account or via a prominent notice on our service platform.",
  },
  point4_2: {
    id: 'point4_2',
    defaultMessage: "It is the user's responsibility to check these Terms and Conditions periodically for changes. Your continued use of or access to the service following the posting of any changes to these Terms and Conditions constitutes acceptance of those changes.",
  },
  point4_3: {
    id: 'point4_3',
    defaultMessage: "Aulasneo may also, in the future, offer new services and/or features through the website (including the release of new tools and resources). Such new features and/or services shall be subject to the current Terms and Conditions.",
  },
  subtitle5: {
    id: 'subtitle5',
    defaultMessage: "User Responsibilities",
  },
  point5_1: {
    id: 'point5_1',
    defaultMessage: "Users must not misuse our services by interfering with their normal operation or attempting to access them using a method other than through the interfaces and instructions provided by us.",
  },
  point5_2: {
    id: 'point5_2',
    defaultMessage: "Users agree not to share their access credentials with others and are responsible for all activities that occur under their account.",
  },
  subtitle6: {
    id: 'subtitle6',
    defaultMessage: "Intellectual Property",
  },
  point6: {
    id: 'point6',
    defaultMessage: "All intellectual property rights in the service and its content, including but not limited to software, documents, text, graphics, logos, and images, are owned by Aulasneo or its licensors. Users may not reproduce, distribute, modify, or create derivative works of any content without explicit permission.",
  },
  subtitle7: {
    id: 'subtitle7',
    defaultMessage: "Disclaimer of Warranties",
  },
  point7: {
    id: 'point7',
    defaultMessage: "PANORAMA is provided 'as is' and on an 'as available' basis. Aulasneo makes no representations or warranties of any kind, express or implied, as to the operation of the service or the information, content, materials, or products included on the service.",
  },
  subtitle8: {
    id: 'subtitle8',
    defaultMessage: "Limitation of Liability",
  },
  point8: {
    id: 'point8',
    defaultMessage: "To the extent permitted by law, Aulasneo shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from the use or inability to use the service.",
  },
  subtitle9: {
    id: 'subtitle9',
    defaultMessage: "Amendments to Terms",
  },
  point9: {
    id: 'point9',
    defaultMessage: "Aulasneo reserves the right to amend these terms and conditions at any time. Your continued use of the service after any changes indicates your acceptance of the new terms.",
  },
  subtitle10: {
    id: 'subtitle10',
    defaultMessage: "Governing Law",
  },
  point10: {
    id: 'point10',
    defaultMessage: "These terms and conditions are governed by the laws of the jurisdiction in which Aulasneo operates. Any disputes related to these terms will be subject to the exclusive jurisdiction of the courts of that jurisdiction.",
  },
  subtitle11: {
    id: 'subtitle11',
    defaultMessage: "Contact Us"
  },
  point11: {
    id: 'point11',
    defaultMessage: "For any questions or concerns about these terms, please contact us at "
  }
});

export default messages;
